name: Update or Create PowerShell Module Documentation
description: |
  Standardized process for creating or updating documentation files for Azure DevOps PowerShell module cmdlets.
  Ensures consistency across all documentation files following PlatyPS schema and module conventions.

instructions: |
  Follow these steps to create or update documentation for PowerShell cmdlets in this module:

  ## 1. Review the PowerShell Function
  - Read the source .ps1 file in src/Azure.DevOps.PSModule/Public/
  - Identify all parameters, their types, defaults, and validation
  - Review the comment-based help (SYNOPSIS, DESCRIPTION, EXAMPLES, OUTPUTS, NOTES)
  - Check the actual output object structure in the code

  ## 2. Documentation File Structure
  Create or update the .md file in docs/ folder with this structure:

  ```markdown
  <!--
  document type: cmdlet
  external help file: Azure.DevOps.PSModule-Help.xml
  HelpUri: [Microsoft Learn URL if available]
  Locale: en-NL
  Module Name: Azure.DevOps.PSModule
  ms.date: [Current Date]
  PlatyPS schema version: 2024-05-01
  title: [Cmdlet-Name]
  -->

  <!-- markdownlint-disable MD024 -->
  <!-- cSpell: ignore dontshow -->

  # [Cmdlet-Name]

  ## SYNOPSIS

  [Brief one-line description]

  ## SYNTAX

  ### __AllParameterSets

  ```text
  Cmdlet-Name [[-Parameter1] <type>] [[-Parameter2] <type>] [-MandatoryParam] <type> [<CommonParameters>]
  ```

  ## ALIASES

  This cmdlet has the following aliases,
  - [Alias1]
  - [Alias2]

  **Note:** If the cmdlet has no function-level aliases, use:
  ```markdown
  ## ALIASES

  This cmdlet has the following aliases,
  - N/A
  ```
  Parameter aliases (like `ProjectId` for `ProjectName`) should be documented in the parameter's YAML section under `Aliases:`, not in this section.

  ## DESCRIPTION

  [Detailed description of what the cmdlet does, 2-3 sentences]

  ## EXAMPLES

  ### EXAMPLE 1

  #### PowerShell

  ```powershell
  $params = @{
      Parameter1 = 'value1'
      Parameter2 = 'value2'
  }
  Cmdlet-Name @params
  ```

  [Description of what the example does]

  ### EXAMPLE 2

  #### PowerShell

  ```powershell
  Cmdlet-Name -Parameter1 'value' -Parameter2 'value'
  ```

  [Description of what the example does]

  ## PARAMETERS

  ### -ParameterName

  [Description]
  [Additional details about behavior or defaults]

  ```yaml
  Type: System.String
  DefaultValue: [default value or empty string]
  SupportsWildcards: false
  Aliases:
  - [Alias if any]
  ParameterSets:
  - Name: (All)
    Position: Named
    IsRequired: [true/false]
    ValueFromPipeline: [true/false]
    ValueFromPipelineByPropertyName: [true/false]
    ValueFromRemainingArguments: false
  DontShow: false
  AcceptedValues:
  - [value1]
  - [value2]
  HelpMessage: ''
  ```

  **IMPORTANT:** Do NOT create separate parameter sections for -WhatIf and -Confirm.
  These are included in the CommonParameters section below.

  ### CommonParameters

  This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
  -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
  -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
  [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).

  ## INPUTS

  - N/A

  ## OUTPUTS

  ### PSCustomObject

  [Description of output object with properties listed]
  - property1: Description
  - property2: Description
  - property3: Description

  ## NOTES

  - [Important notes about the cmdlet]
  - Requires an active Azure account login. Use `Connect-AzAccount` to authenticate:

    ```powershell
    Connect-AzAccount -Tenant '<tenant-id>' -Subscription '<subscription-id>'
    ```

  **NOTE:**
  Connection to Azure DevOps using `Connect-AdoOrganization` is deprecated for new functions that use the `Set-AdoDefault` function
  and automatically authenticate indirectly through the `Invoke-AdoRestMethod` which calls `New-AdoAuthHeader`. This explanation is for
  prompt guidance only and should NOT be included in documentation files.

  ## RELATED LINKS

  - <[Microsoft Learn URL]>
  ```

  **IMPORTANT:** The RELATED LINKS section should ONLY contain external documentation URLs (e.g., Microsoft Learn API references).
  Do NOT include markdown links to other cmdlets in the module (e.g., [Get-AdoCmdlet](Get-AdoCmdlet.md)).

  ## 3. Key Standards

  ### Parameter Documentation
  - Match exact parameter names from .ps1 file
  - Include all aliases listed in [Alias()] attribute
  - Set correct Position (Named for most parameters)
  - Set IsRequired based on [Parameter(Mandatory)] attribute
  - Include DefaultValue from .ps1 file or environment variable
  - List AcceptedValues from [ValidateSet()] attribute

  ### Common Parameters
  - CollectionUri: Optional, default $env:DefaultAdoCollectionUri
  - ProjectName: Optional, default $env:DefaultAdoProject (alias: ProjectId)
  - Version/ApiVersion: Optional, specific to each API endpoint

  ### OUTPUTS Section
  - Use `PSCustomObject` not `System.Object`
  - List all properties returned by the cmdlet
  - Match the actual [PSCustomObject]@{} structure in the .ps1 code
  - Include property descriptions

  ### NOTES Section
  - Include Azure authentication requirement with Connect-AzAccount example
  - Add cmdlet-specific notes from .ps1 file
  - Keep format consistent across all docs

  ### Examples
  - Use splatting (@params) for multi-parameter examples
  - Use direct parameter syntax for simple examples
  - Include meaningful descriptions
  - Test examples to ensure they work

  ## 4. Update Main Module Documentation
  After creating/updating cmdlet docs, ensure the cmdlet is listed in:
  - docs/Azure.DevOps.PSModule.md

  The main module documentation uses a single consolidated table with category headers.
  All cmdlets are organized under category sections within one unified table.

  ### Table Structure:
  - Single table with two columns: Command | Description
  - Category headers are bold rows with empty description: `| **Category Name** | |`
  - Cmdlets are indented using: `| &nbsp; • &nbsp; [Cmdlet-Name](Cmdlet-Name.md) | Brief description |`
  - Categories are listed in alphabetical order
  - Cmdlets within each category are in alphabetical order

  ### Categories (in alphabetical order):
  - **Approvals And Checks** - Check configurations for pipeline resources
  - **Connection and Authentication** - Connection, context, and access token management
  - **Default Context** - Default environment variable management
  - **Environments** - Environment management for pipelines
  - **Features** - Feature state management
  - **Groups and Security** - Group, membership, and descriptor management
  - **Policies** - Policy configuration and type management
  - **Projects and Process** - Project and process management
  - **Repositories** - Repository management
  - **Service Endpoints** - Service endpoint management
  - **Teams** - Team management including settings, iterations, and field values
  - **Work Item Tracking** - Classification node management

  ### Example Entry:
  ```markdown
  | **Connection and Authentication** | |
  | &nbsp; • &nbsp; [Connect-AdoOrganization](Connect-AdoOrganization.md) | Connect to an Azure DevOps organization. |
  | &nbsp; • &nbsp; [Get-AdoContext](Get-AdoContext.md) | Get the current Azure DevOps connection context. |
  ```

  When adding a new cmdlet:
  1. Locate the appropriate category header row in the table
  2. Find the correct alphabetical position within that category
  3. Insert the new row with proper indentation: `| &nbsp; • &nbsp; [Cmdlet-Name](Cmdlet-Name.md) | Brief description |`

  ## 5. Validation Checklist
  - [ ] All parameters match .ps1 function signature
  - [ ] Output type matches [OutputType()] attribute
  - [ ] Output properties match actual PSCustomObject in code
  - [ ] Examples use correct parameter names and values
  - [ ] Aliases are documented
  - [ ] Date is current (ms.date field)
  - [ ] NOTES section includes authentication info
  - [ ] Markdown lint comments added for duplicate headings
  - [ ] Main module doc updated with new cmdlet

examples:
  - pattern: Get-AdoFeatureState.md
    description: Documentation for GET operation that returns multiple objects
    key_features:
      - Multiple feature states returned as collection
      - Feature ID to friendly name mapping documented
      - Environment variable defaults documented

  - pattern: Set-AdoFeatureState.md
    description: Documentation for SET/UPDATE operation
    key_features:
      - ValidateSet values documented
      - Default parameter values specified
      - Output object properties detailed
      - Special notes about feature state behavior

output_format: |
  Generate complete markdown documentation file following the structure above.
  Ensure all sections are complete and accurate to the source .ps1 file.

validation:
  - Check .ps1 file for [OutputType()] attribute
  - Verify all [Parameter()] attributes are documented
  - Match [ValidateSet()] values exactly
  - Confirm default values from param() block
  - Test example code would execute successfully
