# Support the author by using the funding links below.
# Developed and maintained by Martin Swinkels, MSc365 with help from the community.
# GitHub Sponsors: https://github.com/sponsors/msc365
# Buy Me a Coffee: https://www.buymeacoffee.com/msc365

# github: msc365
# buy_me_a_coffee: msc365
#
# Your support means a lot to me to continue the development of open source Azure DevOps Governance projects like this one.
# Sponsoring this project helps cover costs and motivates me to continue building great and meaningful open source projects.
# Thank you for your generosity!
