# Support the author by using the funding links below.
# Developed and maintained by msc365 with help from awesome contributors.
# GitHub Sponsors: https://github.com/sponsors/msc365

github: msc365
# Your support means a lot to me to continue the development of open source projects like this one.
# Sponsoring this project helps cover costs and motivates me to continue building great and meaningful open source tools.
# Thank you for your generosity!
