---
name: "Miscellaneous work \U0001F6E0"
description: 'Create a task for miscellaneous work'
title: '[Miscellaneous] '
labels: ['needs triage :wave:', 'miscellaneous :hammer_and_wrench:']
type: 'task'
projects: ['msc365/3']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for documenting this issue. This template is for miscellaneous tasks like refactoring and improvements.
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for this work.
      options:
        - label: I have searched the existing issues
          required: true
  - type: input
    attributes:
      label: Azure.DevOps.PSModule version
      description: If relevant, please provide the version of the Azure.DevOps.PSModule you are using.
      placeholder: 0.2.0-prev1, 0.2.0, etc.
    validations:
      required: false
  - type: input
    attributes:
      label: Related area or function
      description: Which function(s) or area is related to your request?
      placeholder: New-AdoProject, Multiple functions, Documentation, Test system, etc.
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Type of work
      description: What type of work is this related to?
      multiple: false
      options:
        - Refactoring
        - Technical debt
        - Performance
        - Code quality
        - Documentation
        - Build/CI
        - Deployment/CD
        - Testing
        - Other
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Task description
      description: Describe the task that needs to be done
      placeholder: What should be improved, refactored or done and why?
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance criteria
      description: What are the conditions that must be met for this work to be considered complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: false
  - type: textarea
    id: notes
    attributes:
      label: Additional notes
      description: Any additional context, implementation notes, or considerations
    validations:
      required: false
