---
name: 'Miscellaneous work \U0001F6E0'
description: 'Create an issue for miscellaneous and improvements tasks'
title: '[Miscellaneous] '
labels: ['miscellaneous :hammer_and_wrench:']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for documenting this issue. This template is for miscellaneous refactoring and improvement tasks.
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for this work.
      options:
        - label: I have searched the existing issues
          required: true
  - type: input
    attributes:
      label: Azure.DevOps.PSModule version
      description: Please provide the version of the Azure.DevOps.PSModule you are using.
      placeholder: 0.2.0, 0.2.0-alpha1, etc.
    validations:
      required: true
  - type: input
    attributes:
      label: Related function
      description: Which function is related to your request?
      placeholder: Set-AdoDefault, New-AdoProject, etc.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Improvement description
      description: Describe the refactoring or improvement that needs to be done
      placeholder: What should be refactored or improved and why?
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance criteria
      description: What are the conditions that must be met for this work to be considered complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: false
  - type: textarea
    id: notes
    attributes:
      label: Additional notes
      description: Any additional context, implementation notes, or considerations
    validations:
      required: false
