---
name: "Ask a question \U00002753"
description: 'Ask a question about this project'
title: '[Question] '
labels: ['question :question:']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to ask a question.
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the proposed feature.
      options:
        - label: I have searched the existing issues
          required: true
  - type: input
    attributes:
      label: Azure.DevOps.PSModule version
      description: If relevant, please provide the version of the Azure.DevOps.PSModule you are using.
      placeholder: 0.2.0-prev1, 0.2.0, etc.
    validations:
      required: false
  - type: input
    attributes:
      label: Related function
      description: Which function is related to your question?
      placeholder: Set-AdoDefault, New-AdoProject, etc.
    validations:
      required: false
  - type: textarea
    id: question
    attributes:
      label: Question
      description: Describe the question you have?
    validations:
      required: true
