---
name: "Feature request \U0001F680"
description: 'Suggest an idea for this project'
title: '[Request] '
labels: ['needs triage :wave:', 'enhancement :sparkles:']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out a feature request.
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the proposed feature.
      options:
        - label: I have searched the existing issues
          required: true
  - type: input
    attributes:
      label: Azure.DevOps.PSModule version
      description: Please provide the version of the Azure.DevOps.PSModule you are using.
      placeholder: 0.2.0, 0.2.0-alpha1, etc.
    validations:
      required: true
  - type: input
    attributes:
      label: Related function
      description: Which function is related to your request?
      placeholder: Set-AdoDefault, New-AdoProject, etc.
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Infra as Code type
      description: Are you using Bicep, Terraform, or PowerShell?
      multiple: true
      options:
        - Bicep
        - Terraform
        - PowerShell
        - Other
    validations:
      required: false
  - type: textarea
    id: usecase
    attributes:
      label: Use case
      description: Describe the use case for this feature
      value: |
        **As a** [Role]
        Define the role of the user who will benefit from the feature.

        **I want** [Feature]
        Describe the feature the user wants to use.

        **So that** [Benefit]
        Explain the benefit that the user will gain from the feature.

        **Notes**
        Any additional notes or considerations related to the user story.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe how this feature could be implemented
    validations:
      required: true
